# 用 conda env create -f environment.yml 恢复环境
# Python 3.10.18
name: pinn_env
channels:
  - conda-forge
dependencies:
  # —— 用 conda 装内核/交互层与基础运行时（跨平台更稳）——
  - python=3.10.18
  - pip
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - nest-asyncio
  - packaging
  - parso
  - pickleshare
  - platformdirs
  - prompt-toolkit
  - psutil
  - pygments
  - python-dateutil
  - six
  - stack_data
  - tornado
  - traitlets
  - typing_extensions
  - tzdata
  - zeromq
  - pyzmq
  - setuptools
  - wheel
  - ca-certificates
  - openssl

  # —— 其余用 pip 安装（按你给定的版本为主）——
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - attrs==25.3.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepxde==1.14.0
      - dm-tree==0.1.9
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.0
      - fsspec==2025.9.0
      - gast==0.4.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - idna==3.10
      - jedi==0.19.2
      - Jinja2==3.1.6
      - joblib==1.5.2
      - keras==2.13.1
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - Markdown==3.9
      - MarkupSafe==3.0.2
      - matplotlib==3.10.6
      - mpmath==1.3.0
      - networkx==3.4.2
      - nose==1.3.7
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - pillow==11.3.0
      - protobuf==4.25.8
      - pyaml==25.7.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.5
      - PyYAML==6.0.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scikit-optimize==0.10.2
      - scipy==1.15.3
      - svn==1.0.1
      - sympy==1.14.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - urllib3==2.5.0
      - Werkzeug==3.1.3
      - wrapt==1.17.3
